name: Release
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_username: __token__
          repository_password: ${{ secrets.PYPI_TOKEN }}
#      - name: Semantic Release
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
##          REPOSITORY_USERNAME: __token__
#        run: |
#          pip install python-semantic-release
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          poetry run semantic-release print-version --current
#          poetry run semantic-release print-version
##          poetry run semantic-release publish
#      - name: Publish
#        env:
#          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
#        run: |
#          poetry config pypi-token.pypi $PYPI_TOKEN
#          poetry publish --build